# Generated by Django 6.0.6 on 2026-06-16 21:27

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('transplant_date', models.DateField(blank=True, null=True)),
                ('transplant_type', models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Liver', 'Liver'), ('Kidney', 'Kidney')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stool_id', models.IntegerField()),
                ('aliquots', models.IntegerField()),
                ('date_collected', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plt.patient')),
            ],
            options={
                'unique_together': {('patient_id', 'stool_id')},
            },
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.IntegerField()),
                ('sample_type', models.CharField(choices=[('VRE', 'VRE'), ('ESBL', 'ESBL'), ('KPC', 'kPC')], max_length=10)),
                ('amount', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('stool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plt.stool')),
            ],
            options={
                'unique_together': {('stool_id', 'isolate_id')},
            },
        ),
        migrations.CreateModel(
            name='TaggedArg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Arg Tag',
            },
        ),
        migrations.CreateModel(
            name='WGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(max_length=25)),
                ('depth', models.FloatField()),
                ('organism', models.CharField(max_length=50)),
                ('arg', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='plt.TaggedArg', to='taggit.Tag', verbose_name='Tags')),
                ('isolate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wgs_plt_isolate_id', to='plt.isolate')),
            ],
            options={
                'verbose_name': 'WGS',
                'verbose_name_plural': 'WGS',
            },
        ),
        migrations.AddField(
            model_name='taggedarg',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plt.wgs'),
        ),
        migrations.CreateModel(
            name='IsolateStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_letter', models.CharField(editable=False, max_length=1)),
                ('box', models.CharField(editable=False, max_length=13)),
                ('position', models.IntegerField(editable=False)),
                ('isolate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plt.isolate')),
            ],
            options={
                'unique_together': {('box', 'position'), ('isolate_id', 'stock_letter')},
            },
        ),
        migrations.CreateModel(
            name='StoolAliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquot', models.CharField(editable=False, max_length=10)),
                ('box', models.CharField(editable=False, max_length=13)),
                ('position', models.IntegerField(editable=False)),
                ('stool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plt.stool')),
            ],
            options={
                'unique_together': {('box', 'position'), ('stool_id', 'aliquot')},
            },
        ),
    ]
