# Generated by Django 6.0.6 on 2026-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='transplant_date',
            new_name='consent_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='transplant_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Withdrawn', 'Withdrawn'), ('Excluded', 'Excluded'), ('Completed', 'Completed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_cub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='txp_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
