# Generated by Django 6.0.6 on 2026-06-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=6)),
                ('sample_num', models.IntegerField()),
                ('sample_type', models.CharField(choices=[('P', 'Patient'), ('E', 'Environmental'), ('D', 'Drain')], default='P', max_length=3)),
                ('sixteen_s', models.BooleanField(default=True)),
                ('extraction', models.BooleanField(blank=True, default=None, null=True)),
                ('sixteen_s_finished', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('box', models.IntegerField()),
                ('position', models.CharField(max_length=2)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"freedberg"."sample"',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vre_blue', models.BooleanField(default=False)),
                ('vre_pink', models.BooleanField(default=False)),
                ('kpc_blue', models.BooleanField(default=False)),
                ('kpc_pink', models.BooleanField(default=False)),
                ('kpc_white', models.BooleanField(default=False)),
                ('kpc_yellow', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedberg.sample')),
            ],
            options={
                'db_table': '"freedberg"."culture"',
                'unique_together': {('sample_id',)},
            },
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.CharField(editable=False, max_length=7)),
                ('isolate_type', models.CharField(choices=[('vre_blue', 'VRE Blue'), ('vre_pink', 'VRE Pink'), ('kpc_blue', 'KPC Blue'), ('kpc_pink', 'KPC Pink'), ('kpc_white', 'KPC White'), ('kpc_yellow', 'KPC Yellow')], max_length=10)),
                ('box', models.CharField(editable=False, max_length=25)),
                ('position', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('EXT', 'Colony Extracted'), ('LIB', 'Library Prepped'), ('WGS', 'Sequenced')], default='NEW', max_length=3)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolate_by_id', to='freedberg.culture')),
            ],
            options={
                'db_table': '"freedberg"."isolate"',
                'unique_together': {('box', 'position')},
            },
        ),
    ]
